# Generated by Django 3.2.16 on 2023-12-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=50, help_text='цена'),
        ),
    ]
